services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: samurai
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - samurai_db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - samurai_redis:/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: samurai_api
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis

  worker_1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: samurai_worker_1
    command: python -m app.workers.consumer_entrypoint
    env_file:
      - .env
    depends_on:
      - redis
      - postgres

  worker_2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: samurai_worker_2
    command: python -m app.workers.consumer_entrypoint
    env_file:
      - .env
    depends_on:
      - redis
      - postgres

volumes:
  samurai_db:
  samurai_redis:
